version: '3'

name: mlflow_api
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ricofebrian405/mlflow_api
    container_name: mlflow_api
    ports:
      - 8080:8080
    env_file:
      - .env